### ISSUE TITLE
Real User Monitoring

### ISSUE THREAD

**Issue by sundarv85** [switowski/deploystack#20]
Already listed in Roadmap (issue #1). Just added so that it can be tracked as a separate issue here.

Thoughts about adding it as a separate new section?

**Comment by switowski** [comment]
Hi @sundarv85,
I didn't manage to sit down and do some more reading on this topic yet (as I'm not very familiar with Real User Monitoring), but I have just set the atatus to test how it works.
From what I can see, Real User Monitoring is a combination of standard analytics tools (like google analytics, where you can see how many users visits your pages, total time spent, sessions, etc.), page load times (that you can also get from uptime monitoring tools) and errors (that you can get from, well, error monitoring tools :) ). Of course, it's more convenient to use one tool for RUM, than to gather data from 3 different ones, so that's a good tool and definitely worth describing. Are there any other, important features that I'm missing?
Do you know about any free tools for Real User Monitoring (or companies with free tiers)? I see that NewRelic has a Lite plan, but with very little features.
Do you have any experience with using any of the tools that you have suggested in #1 ?

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
