### ISSUE TITLE
Add option for EV SSL certs

### ISSUE THREAD

**Issue by mikemaccana** [switowski/deploystack#6]
LE is awesome, but it only does DV certs. If you want an EV cert (like 'GitHub, Inc. [US]' on this site), CertSimple is [way better](https://certsimple.com/about) than Symantec, GoDaddy and Comodo).

**Comment by switowski** [comment]
Hi Mike, thanks for creating the issue and thanks for making the effort with the PR, I will take a look at the EV certificates and see what other options are there (until today I didn't know there are other options than a "standard SSL" certificate). To include this additional sub-section on the page, I will probably have to redesign it a bit (a got a lot of feedback today, so that might take a while, but please stay tuned).

**Comment by mikemaccana** [comment]
Awesome - thanks Sebastian! There's an overview of some of the other SSL focused startups at https://certsimple.com/blog/certsimple-v5-doing-business-as-ev-https
