### ISSUE TITLE
Sentry for Error Tracking

### ISSUE THREAD

**Issue by pirate** [switowski/deploystack#9]
Sentry seems to be more widely used than Rollbar, Airbrake, or Raygun, can it be listed under the "Error Tracking" section?
https://sentry.io/welcome/

**Comment by bonndan** [comment]
https://www.bugsnag.com/

I've made very good experience with bugsnag. However, what is the criteria to be listed on deploystack?

**Comment by switowski** [comment]
Hi @pirate , thanks for the suggestion with Sentry, I have added it to the list (539665fabc1).

**Comment by switowski** [comment]
Hi @bonndan , there are no strict criteria, but I try to select companies/tools that:
- offer good value for money
- are developer-friendly: good documentation and support, recommended by other developers on hacker news or reddit, offer free plans, etc.
I also try to keep the list of options small (listing 10 companies doesn't make sense, because it would be hard to make a good comparison between all of them and it won't be helpful to new developers). You can read more details on https://deploystack.io/faq page.

Bugsnag looks great, but I don't see any distinctive features that would convince me to choose Bugsnag over other companies already recommended on DeployStack. Unless I'm wrong and there are some features of Bugsnag that no other company has - if you know about any, I would love to hear it :)

**Comment by switowski** [comment]
Closing, sentry has been added
